# Generated by Django 4.1.12 on 2023-10-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jk', '0002_meterreading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meterreading',
            name='reading_period',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
